# Generated by Django 2.1.2 on 2019-03-27 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('custom_data', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('custom_data', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.Context')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('version', models.IntegerField()),
                ('content', models.TextField()),
                ('custom_data', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wiki.Document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
