# Generated by Django 2.1.2 on 2019-03-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='changed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='wiki.Document'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('context', 'name')},
        ),
    ]
