# Generated by Django 2.1.2 on 2019-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190327_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='custom_data',
            field=models.CharField(blank=True, db_index=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='custom_data',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
