# Generated by Django 3.0.7 on 2020-06-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20190404_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='context',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='context',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
