# Generated by Django 2.1.2 on 2019-04-04 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproperty',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='text_properties', to='issues.Issue'),
        ),
        migrations.AlterField(
            model_name='userproperty',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_properties', to='issues.Issue'),
        ),
    ]
