# Generated by Django 2.1.2 on 2019-04-04 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190309_0600'),
        ('issues', '0002_auto_20190404_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Room'),
            preserve_default=False,
        ),
    ]
