# Generated by Django 2.2a1 on 2019-02-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unread', '0002_auto_20190224_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemtime',
            name='data',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='systemtime',
            name='system',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='data',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='usertime',
            name='system',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
