# Generated by Django 2.2a1 on 2019-02-26 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unread', '0003_auto_20190225_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(db_index=True, max_length=255)),
                ('data', models.BigIntegerField(db_index=True)),
                ('subscription_type', models.CharField(choices=[('active', 'Active'), ('passive', 'Passive')], db_index=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'system', 'data')},
            },
        ),
    ]
