# Generated by Django 2.1.2 on 2019-03-24 04:57
from functools import partial

from django.conf import settings
from django.db import migrations, models


def migrate_identifier(apps, schema_editor, table):
    del schema_editor
    M = apps.get_model("unread", table)
    for o in M.objects.all():
        o.identifier = f'{o.system}_{o.data}'
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('unread', '0004_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='identifier',
            field=models.CharField(db_index=True, default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemtime',
            name='identifier',
            field=models.CharField(db_index=True, default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertime',
            name='identifier',
            field=models.CharField(db_index=True, default='', max_length=512),
            preserve_default=False,
        ),

        migrations.RunPython(partial(migrate_identifier, table='Subscription')),
        migrations.RunPython(partial(migrate_identifier, table='SystemTime')),
        migrations.RunPython(partial(migrate_identifier, table='UserTime')),

        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'identifier',)},
        ),
        migrations.AlterUniqueTogether(
            name='systemtime',
            unique_together={('identifier',)},
        ),
        migrations.AlterUniqueTogether(
            name='usertime',
            unique_together={('user', 'identifier')},
        ),
    ]
