# Generated by Django 2.1.2 on 2019-03-24 06:11
from functools import partial

from django.db import migrations


def migrate_identifier(apps, schema_editor, table):
    del schema_editor
    M = apps.get_model("unread", table)
    for o in M.objects.all():
        o.identifier = o.identifier.replace('forum_room_', 'forum/room:')
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('unread', '0005_auto_20190324_0457'),
    ]

    operations = [
        migrations.RunPython(partial(migrate_identifier, table='Subscription')),
        migrations.RunPython(partial(migrate_identifier, table='SystemTime')),
        migrations.RunPython(partial(migrate_identifier, table='UserTime')),
    ]
