# Generated by Django 2.1.2 on 2019-03-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unread', '0006_auto_20190324_0611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='data',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='system',
        ),
        migrations.RemoveField(
            model_name='systemtime',
            name='data',
        ),
        migrations.RemoveField(
            model_name='systemtime',
            name='system',
        ),
        migrations.RemoveField(
            model_name='usertime',
            name='data',
        ),
        migrations.RemoveField(
            model_name='usertime',
            name='system',
        ),
    ]
