# Generated by Django 2.2a1 on 2019-02-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='words',
        ),
        migrations.RemoveField(
            model_name='room',
            name='mode',
        ),
    ]
