# Generated by Django 2.2a1 on 2019-02-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190218_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
