# Generated by Django 2.1.2 on 2019-03-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='custom_data',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='custom_data',
            field=models.CharField(blank=True, db_index=True, max_length=1024, null=True),
        ),
    ]
